export const basePermissions = [
  'users:create',
  'users:read',
  'users:update',
  'users:delete',
  'roles:manage',
  'permissions:manage',
  'customers:create',
  'customers:read',
  'customers:update',
  'customers:delete',
  'customers:assign',
  'contacts:create',
  'contacts:read',
  'contacts:update',
  'contacts:delete',
  'leads:create',
  'leads:read',
  'leads:update',
  'leads:delete',
  'leads:assign',
  'leads:convert',
  'deals:create',
  'deals:read',
  'deals:update',
  'deals:delete',
  'deals:close',
  'quotes:create',
  'quotes:read',
  'quotes:update',
  'quotes:approve',
  'quotes:send',
  'quotes:delete',
  'orders:create',
  'orders:read',
  'orders:update',
  'orders:cancel',
  'products:create',
  'products:read',
  'products:update',
  'products:delete',
  'inventory:read',
  'inventory:adjust',
  'inventory:transfer',
  'tickets:create',
  'tickets:read',
  'tickets:update',
  'tickets:assign',
  'tickets:close',
  'reports:read',
  'settings:update',
  'audit:read',
] as const;

export type BasePermission = (typeof basePermissions)[number];

export const baseRoles = [
  'Super Admin',
  'Admin',
  'Sales Manager',
  'Sales Representative',
  'Support Manager',
  'Support Agent',
  'Warehouse Manager',
  'Warehouse User',
  'Finance Viewer',
  'Read Only',
] as const;

export type BaseRole = (typeof baseRoles)[number];

